1. Which of these clauses will be executed even if no exceptions are found?
a) throws
b) finally
c) throw
d) catch
b
2. A single try block must be followed by which of these?
a) finally
b) catch
c) Both finally & catch
d) None of the mentioned
c
3. Which of these exceptions handles the divide by zero error?
a) ArithmeticException
b) MathException
c) IllegalAccessException
d) IllegarException
a
4. Which of these exceptions will occur if we try to access the index of an array beyond its length?
a) ArithmeticException
b) ArrayException
c) ArrayArguementException
d) IndexOutOfRangeException
d
5. What will be the output of the following C# code snippet?
   class program   {       public static void Main(string[] args)       {           try            {               int a = args.Length;               int b = 1 / a;               Console.WriteLine(a);           }           catch (ArithmeticException e)            {               Console.WriteLine("1");           }           Console.ReadLine();       }   }
a) 0
b) 1
c) Compile time error
d) Runtime error
b
6. What will be the output of the following C# code snippet?
 class program {     public static void Main(string[] args)     {         try         {             throw new NullReferenceException("C");             Console.WriteLine("A");         }         catch (ArithmeticException e)          {             Console.WriteLine("B");         }         Console.ReadLine();     } }
a) A
b) B
c) Compile time error
d) Runtime error
d
7. What will be the output of the following C# code snippet?
 class Program {     public static void Main(string[] args)     {         try         {             int a = 1;             int b = 10 / a;             try             {                 if (a == 1)                     a = a / a - a;                 if (a == 2)                 {                     int[] c = { 1 };                     c[8] = 9;                 }             }             finally             {                 Console.WriteLine("A");             }        }        catch (IndexOutOfRangeException e)        {             Console.WriteLine("B");        }        Console.ReadLine();    } }
a) A
b) B
c) AB
d) BA
a
8. What will be the output of the following C# code snippet?
 class Program {     public static void Main(string[] args)     {         try         {             int a = args.Length;             int b = 10 / a;             Console.WriteLine(a);             try             {                 if (a == 1)                 a = a / a - a;                 if (a == 2)                 {                     int[] c = { 1 };                     c[8] = 9;                 }             }             catch (IndexOutOfRangeException e)             {                 Console.WriteLine("TypeA");             }         }         catch (ArithmeticException e)         {             Console.WriteLine("TypeB");         }         Console.ReadLine();     } }
a) TypeA
b) TypeB
c) 0TypeA
d) Compile time error
b
9. Which of the following keywords is used by the calling function to guard against the exception that is thrown by called function?
a) try
b) throw
c) throws
d) catch
c
10. Which of these classes is related to all the exceptions that are explicitly thrown?
a) Error
b) Exception
c) Throwable
d) Throw
c
Sanfoundry Global Education & Learning Series – C# Programming Language.
Here’s the list of Best Reference Books in C# Programming Language.
To practice all areas of C# for Interviews, here is complete set on 1000+ Multiple Choice Questions and Answers on C#.
Participate in the Sanfoundry Certification contest to get free Certificate of Merit. Join our social networks below and stay updated with latest contests, videos, internships and jobs!
Telegram | Youtube | LinkedIn | Instagram | Facebook | Twitter | Pinterest
Youtube | LinkedIn | Instagram | Facebook | Twitter | Pinterest
« Prev - C# Questions & Answers – Implementation of Exception Handling» Next - C#Questions & Answers – Try & Catch in Detail 
